SHORTEN_URL_ENDPOINT = "/api/shorten/"
GET_ORIGINAL_URL_ENDPOINT = "/api/"
URL_STATS_ENDPOINT = "/api/stats/"

TEST_ORIGINAL_URL = "https://example.com"
EXPECTED_SHORTENED_URL = "abc123"
EXPECTED_SHORTENED_URL_2 = "abc124"
ERROR_MESSAGE_URL_NOT_FOUND = "URL not found"
